version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    vite:
      patterns:
        - "vite_rails"
        - "vite_ruby"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    vite:
      patterns:
        - "vite"
        - "vite-plugin-*"
    tailwindcss:
      patterns:
        - "@tailwindcss/*"
        - "tailwindcss"
        - "daisyui"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
